name: YG's Programming World
markdown: rdiscount
permalink: /:year/:month/:day/:title.html
pygments: true
timezone: Asia/Shanghai
safe: true
encoding: UTF-8
email: gangyou@gmail.com
url: http://www.yougang.info
production_url: http://www.yougang.info
